### ISSUE TITLE
Error Loading the monaco editor module

### ISSUE THREAD

**Issue by david10sing** [JeremyRH/storybook-addon-code-editor#1]
Hi,

I am currently trying to include your package as a live code editor / preview an mdx file outside of storybook.

However, in the `loadMonacoEditor` function, I am getting an error. I think it might be because it is trying to load the `loader.js` file and cannot find it.

Is there some missing setup information? Do we need to somehow install monaco first and set it up?

I am looking at your package and think that it could be used in more than just storybook.

**Comment by JeremyRH** [comment]
Monaco's build comes with [monaco-editor/min/vs/loader.js](https://unpkg.com/browse/monaco-editor@0.34.1/min/vs/loader.js) but it requires the other built files in [monaco-editor/min/vs/](https://unpkg.com/browse/monaco-editor@0.34.1/min/vs/) to be available. This means monaco-editor/min/vs/ has to be hosted somewhere so the browser can fetch these files.

I did this by [configuring webpack to copy monaco-editor/min/vs/](https://github.com/JeremyRH/storybook-addon-code-editor/blob/dbe9ef6308bc1cb1c7093c5c79dfcd6f6625c63f/src/preset.ts#L8-L9) and [configured RequireJS](https://github.com/JeremyRH/storybook-addon-code-editor/blob/dbe9ef6308bc1cb1c7093c5c79dfcd6f6625c63f/src/loadMonacoEditor.ts#L19-L20) (used by loader.js) to use the directory.

It would be nice if Monaco provided a loader using dynamic imports.
