### ISSUE TITLE
Imports in code-editor showing error

### ISSUE THREAD

**Issue by sanju-developer** [JeremyRH/storybook-addon-code-editor#19]
Hey @JeremyRH 

I'm using mui material and I have noticed one error --> The imports in "Live-code-editor" adon on browser shows imports error. Share in picture below

![image](https://user-images.githubusercontent.com/45697130/231102595-85221199-89fb-4cbb-87bc-621fd5e720a4.png)

on hover the error says: `Cannot find module '@mui/material' or its corresponding type declarations.(2307)`. Also other relative path imports are also showing same import error.

Import statement similar to this `@mui/material` working fine in other files. Could you please share your thoughts why it's looks like this?

**Comment by sanju-developer** [comment]
Also, Suppose someone using these `stories.tsx` file in their test cases and these file have import of raw file like `Playground.source.tsx?raw`, then during `yarn test` or `npm test` it's failing with error: 

` Cannot find module './Playground.source.tsx?raw' from 'stories/test/Playground.stories.tsx'`

Did you see this or any way ?

**Comment by JeremyRH** [comment]
For `Cannot find module '@mui/material' or its corresponding type declarations.`, a types lib needs to be added to monaco:
```js
// .storybook/preview.js
import { setupMonaco } from 'storybook-addon-code-editor';

setupMonaco({
  onMonacoLoad(monaco) {
    monaco.languages.typescript.typescriptDefaults.addExtraLib(
      'declare module "@mui/material";',
      'file:///node_modules/@mui/material/index.d.ts'
    );
  },
});
```

This will not give you the real types for `@mui/material`. It will stop the error and give you `any` type for all imports `from '@mui/material'`.
You would have to generate a single type file for `@mui/material` and import it as `?raw` string to get the correct types. Might not be feasible.

For tests failing when encountering `?raw` imports, you might be able to set up your test runner to stub them.
Jest can do this with [moduleNameMapper](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring).

**Comment by JeremyRH** [comment]
Closing to clean up old issues. Hopefully your issues were solved.
