### ISSUE TITLE
Unable to  launch following install instructions

### ISSUE THREAD

**Issue by michaeltford** [JeremyRH/storybook-addon-code-editor#21]
I get the following error when trying to load. Am I missing something obvious? I appears to be a babel related issue.

ModuleNotFoundError: Module not found: Error: Can't resolve '@babel/plugin-syntax-unicode-sets-regex' in 'C:\dev\sheetxl\node_modules\@babel\standalone'.

When trying to troubleshoot I downloaded the source and tried to run the example (I am on a windows 11 box).  I get the following error
Cannot find module './dist/cjs/preset'

**Comment by michaeltford** [comment]
Thanks @svanetten1976 . I am not new to development and I spent several hours with no luck. I also tried in sb 7.1alpha with fresh download. This component looks so awesome. 

It has something to do with babel standalone needed for monaco but sb is include/mapping.

**Comment by JeremyRH** [comment]
Thanks for reporting, I'll take a look at this soon.

**Comment by svanetten1976** [comment]
@michaeltford @JeremyRH I actually just solved the issue, figured out what I needed to do anyways with my configuration. This is the magic line, maybe this is something you want to add : 
`      '@babel/plugin-syntax-unicode-sets-regex': path.resolve(__dirname, '../', 'node_modules/@babel/standalone')`

This is in storybook/main.ts in my case, here is the full webpackFinal function (there is some other stuff in there very specific to the app I am working on but that is the magic line that fixed stuff for me):

```
  webpackFinal: async (config) => {
    // Use SVGR for SVG files
    const fileLoaderRule = config.module.rules.find((rule) => (rule as any).test.test('.svg'));
    (fileLoaderRule as any).exclude = /\.svg$/;
    config.module.rules.push({
      test: /\.svg$/,
      use: [
        { loader: '@svgr/webpack', options: { icon: true } },
        {
          loader: 'file-loader',
          options: {
            name: '[name].[contenthash].[ext]',
          },
        },
      ],
    });

    config.resolve.alias = {
      '@babel/plugin-syntax-unicode-sets-regex': path.resolve(__dirname, '../', 'node_modules/@babel/standalone'),
      '@': path.resolve(__dirname, '../', 'src'),
    };

    return config;
  },

```

**Comment by michaeltford** [comment]
@svanetten1976, very nice job! I thought about an alias but I thought there might be a ton more. I will try this patch tomorrow and thanks. @JeremyRH do you think this is a storybook issue or a monaco issue? I didn't see anything in your codebase that looked like it would cause this.

**Comment by JeremyRH** [comment]
`@babel/standalone` has this in it's JS:
```js
require("@babel/plugin-syntax-unicode-sets-regex")
```
but it does not have `@babel/plugin-syntax-unicode-sets-regex` as a dependency or peer dependency. Maybe this was working before due to storybook or some other dependency bringing in `@babel/plugin-syntax-unicode-sets-regex` and now it's not.

**Comment by JeremyRH** [comment]
This was fixed on babel's side: https://github.com/babel/babel/pull/15675/files
