### ISSUE TITLE
Error: Cannot find module 'monaco-editor' 

### ISSUE THREAD

**Issue by rdangol1** [JeremyRH/storybook-addon-code-editor#30]
I am getting a cannot find module 'monaco-editor' at getStaticDir error. I have added "monaco-editor": "^0.39.0" to dependencies along with "@storybook/builder-webpack5": "^6.5.16" and "@storybook/manager-webpack5": "^6.5.16" to dev dependencies in storybook 7. Not sure I'm missing a step or doing something wrong and would appreciate some help.

**Comment by JeremyRH** [comment]
What package manager (plus the version) are you using?

**Comment by rdangol1** [comment]
yarn 3.6.1

**Comment by JeremyRH** [comment]
Thanks. Are you using Plug'n'Play or Zero Installs?

**Comment by rdangol1** [comment]
It's zero install. And thank for the quick help.

**Comment by rdangol1** [comment]
Thank you!
