### ISSUE TITLE
SyntaxError: /index.tsx: Unexpected token, expected "," 

### ISSUE THREAD

**Issue by rdangol1** [JeremyRH/storybook-addon-code-editor#34]
Hey Jeremy,

I get this error below in storybook when I try to add the editable story. I'm not entirely sure if I'm missing anything but would appreciate some help. 

Code for Button.Source.tsx
```
import * as React from 'react';
import { Button } from '../..';

const ButtonStory = React.forwardRef((props, ref) => {
  return (
    <>
      <Button />
      <div>xx</div>
    </>
  )

});

export default ButtonStory;
```
Button.stories.tsx
```
import { createLiveEditStory } from 'storybook-addon-code-editor';
import ButtonStory from './Button.source';

export const EditableStoryJSSource = createLiveEditStory({
  code: ButtonStory as any,
});
```
![Screenshot 2024-03-04 at 12 06 50 PM](https://github.com/JeremyRH/storybook-addon-code-editor/assets/65328698/3bf5fa57-94d1-4709-a014-9e85d048a781)

**Comment by JeremyRH** [comment]
I think the issue is you need a `?raw` at the end of `import ButtonStory from './Button.source';`. `?raw` will import the file as a string.

Try this:
```js
import ButtonStory from './Button.source?raw'';
```

Hopefully this fixes it. I don't know if you need the file extension also. Try this if the above doesn't work:
```js
import ButtonStory from './Button.source.tsx?raw'';
```

**Comment by rdangol1** [comment]
Thank you for the quick help. The above solution solved the error above  but I still get his second error. Would you have some idea?
<img width="941" alt="Screenshot 2024-03-11 at 5 27 08 PM" src="https://github.com/JeremyRH/storybook-addon-code-editor/assets/65328698/1940e25e-1a9b-440a-893b-6cc389379062">

**Comment by JeremyRH** [comment]
In the screenshot, I see the editor is empty, causing the error because there is no default export (there's no code at all).
At this point it would be more efficient if you share a repo that reproduces the issue.

This is probably a type-o with `import ButtonStory from './Button.source.tsx?raw';` or a storybook config issue.

**Comment by rdangol1** [comment]
Yep, you were right. I finally got it up and running. Thank you for all your help.
