### ISSUE TITLE
Addon Panel Missing in Storybook 8

### ISSUE THREAD

**Issue by lyleaigbedion** [JeremyRH/storybook-addon-code-editor#35]
Hi I am able to view the component but I cannot access the editor in my storybook addons.

**Comment by lyleaigbedion** [comment]
I found that it requires installing `@storybook/manager-api` and replacing `@storybook/addons` imports and api signatures in the `register.tsx` file: 

`addPanel` -> `add`
 And Removing `key` from `<AddonPanel/>`

Since this updates dependencies, I'd rather someone with more knowledge ensure it works for more than just me.

**Comment by JeremyRH** [comment]
Thank you for reporting and exploring a fix for this. I have not prioritized updating this addon to work with Storybook 8 because I assumed it would take 10s of hours.

It might be a simple fix! I'll work on this today.

**Comment by JeremyRH** [comment]
Should be fixed with #38 
`storybook-addon-code-editor@3.0.0` is the version.
