### ISSUE TITLE
Loading React types does not work anymore

### ISSUE THREAD

**Issue by wintercounter** [JeremyRH/storybook-addon-code-editor#4]
Since they added `exports` field, `index.d.ts` cannot be imported anymore directly like in the sample code.

```
Module not found: Error: Package path ./index.d.ts?raw is not exported from package /Users/***/GITHUB/gdm-ui/node_modules/@types/react (see exports field in /Users/***/GITHUB/gdm-ui/node_modules/@types/react/package.json)
```

This isn't directly a bug in the addon, but it makes the example invalid.

**Comment by wintercounter** [comment]
I see in code this is already resolved by DefinePlugin, but I leave the issue open since in README this is not reflected.

**Comment by JeremyRH** [comment]
Can you point me to where it's out of date? Sorry, I know the README isn't very thorough and could be improved.

**Comment by wintercounter** [comment]
I honestly didn't check the current Readme and I copied form here: https://storybook.js.org/addons/storybook-addon-code-editor

I expected this to be in sync with the repo, seems like I was wrong. This still has the old example for me, but I guess not much you can do here.

**Comment by JeremyRH** [comment]
I see the old README there too. I guess it takes time for them to update it.

**Comment by JeremyRH** [comment]
React type definitions are loaded automatically in v2. [See changes here](https://github.com/JeremyRH/storybook-addon-code-editor/releases/tag/v2.0.0).
