### ISSUE TITLE
Controlled Input loses focus after entering every character

### ISSUE THREAD

**Issue by chaithalbe** [JeremyRH/storybook-addon-code-editor#40]
When i try to type anything into the input, it loses focus after every key hit.

Versions:

```
storybook: 8.0.10
storybook-addon-code-editor: 3.0.0
```

Code:

```ts
import { createLiveEditStory } from 'storybook-addon-code-editor';
import * as React from 'react';

export const EditableStory = createLiveEditStory({
  availableImports: {
    'react': React,
  },
  code: `import { useState } from 'react';

const [value, setValue] = useState();

const handleChange = (e) => {
  setValue(e.target.value);
}

const TextFieldExample = (props) => {
  return <input value={value} onChange={handleChange} />;
};

export default TextFieldExample;`,
});
```

This happens only when I use live code editor. It does not happen when I use a story like below:

```ts
export const PhoneInputWithLabelElement: StoryFunc = () => {
  const [value, setValue] = useState();

  const handleChange = (e) => {
    setValue(e.target.value);
  }

  return (
      <input
          value={value}
          onChange={handleChange}
      />
  );
};
```

**Comment by JeremyRH** [comment]
Calling `useState` outside`TextFieldExample` causes React to re-render and a new instance of `TextFieldExample` is created. This new instance causes React DOM to remove the previous `<input />` and add a new one, making it seem like focus is lost.

Move these lines inside the `TextFieldExample` function:
```js
const [value, setValue] = useState();

const handleChange = (e) => {
  setValue(e.target.value);
}
```

You shouldn't call hooks outside a component. Normally React would raise an error but with how storybook-addon-code-editor is implemented, the outside scope is technically run during the render phase of a React component. Maybe I can add a check for this.

**Comment by chaithalbe** [comment]
My bad, thank you so much for the quick response.
